// Generates css/fonts.css and fills fonts/ with only the woff2 files the site needs.
// Run it after changing text that adds new Japanese characters:   node scripts/fonts.mjs
//
// Each fonts/<family>/source.css is the original @fontsource stylesheet (data only, never loaded
// by the browser). Barlow Condensed and Work Sans keep their latin + latin-ext subsets.
// M PLUS 1 Code has ~120 Japanese chunks; we keep latin + latin-ext + the chunks covering
// characters used in index.html and the JS. Missing font files are downloaded once from jsDelivr
// (the same @fontsource files), and files no longer referenced are removed.
// Characters outside the kept chunks still render, with the system Japanese font.
import { readFileSync, writeFileSync, readdirSync, existsSync, unlinkSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const FAMILIES = [
    { dir: 'barlow-condensed', pkg: '@fontsource/barlow-condensed@5.3.0', subsetByText: false },
    { dir: 'work-sans', pkg: '@fontsource/work-sans@5.3.0', subsetByText: false },
    { dir: 'm-plus-1-code', pkg: '@fontsource/m-plus-1-code@5.3.0', subsetByText: true },
];

// every non-ASCII code point used on the site
const sources = [
    join(root, 'index.html'),
    ...readdirSync(join(root, 'js')).filter((f) => f.endsWith('.js')).map((f) => join(root, 'js', f)),
];
const used = new Set();
for (const file of sources) {
    for (const ch of readFileSync(file, 'utf8')) {
        const cp = ch.codePointAt(0);
        if (cp > 0x7f) used.add(cp);
    }
}

const covers = (range) => range.split(',').some((part) => {
    const [a, b] = part.trim().replace(/^U\+/i, '').split('-').map((h) => parseInt(h, 16));
    for (const cp of used) if (cp >= a && cp <= (b ?? a)) return true;
    return false;
});

const out = ['/* Generated by scripts/fonts.mjs: do not edit. Run `node scripts/fonts.mjs` after changing text. */'];

for (const family of FAMILIES) {
    const dir = join(root, 'fonts', family.dir);
    const css = readFileSync(join(dir, 'source.css'), 'utf8');
    const blocks = [...css.matchAll(/\/\* ([^ ]+) \*\/\s*@font-face \{([\s\S]*?)\}/g)];

    const kept = blocks.filter(([, name, body]) => {
        if (/-latin(-ext)?-\d+-normal$/.test(name)) return true;
        if (!family.subsetByText) return false;
        const range = body.match(/unicode-range:\s*([^;]+);/);
        return range && covers(range[1]);
    });

    const files = new Set();
    for (const [, name, body] of kept) {
        const file = body.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
        files.add(file);
        const cleaned = body.replace(/src:[^;]+;/, `src: url(../fonts/${family.dir}/${file}) format('woff2');`);
        out.push(`/* ${name} */\n@font-face {${cleaned}}`);
    }

    // fetch missing files, drop unused ones
    for (const file of files) {
        if (existsSync(join(dir, file))) continue;
        const url = `https://cdn.jsdelivr.net/npm/${family.pkg}/files/${file}`;
        const res = await fetch(url);
        if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
        writeFileSync(join(dir, file), Buffer.from(await res.arrayBuffer()));
        console.log(`  downloaded ${file}`);
    }
    for (const file of readdirSync(dir)) {
        if (file.endsWith('.woff2') && !files.has(file)) {
            unlinkSync(join(dir, file));
            console.log(`  removed ${file}`);
        }
    }

    console.log(`${family.dir}: ${kept.length} of ${blocks.length} @font-face blocks`);
}

writeFileSync(join(root, 'css/fonts.css'), out.join('\n\n') + '\n');
console.log(`css/fonts.css written (${used.size} non-ASCII characters on the site)`);
